apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: api-gateway-conf
      containers:
        - name: api-gateway
          image: nginx:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
---
{{/* NGinx Configuration file = /etc/nginx/conf.d/default.conf */}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: api-gateway-conf
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
          proxy_pass http://gateway-service;
      }
    }