{{- range $svcKey, $svc := .Values.codehorn.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $svc.name }}
  labels:
    app: {{ $svc.name }}
spec:
  replicas: {{ $svc.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $svc.name }}
  template:
    metadata:
      labels:
        app: {{ $svc.name }}
    spec:
      containers:
        - name: {{ $svc.name }}
          image: {{ $svc.image }}
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          envFrom:
            - configMapRef:
                name: {{ $.Values.codehorn.configs.serviceDiscovery.name }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ $svc.name }}
spec:
  selector:
    app: {{ $svc.name }}
  ports:
    - port: 80
      targetPort: 80
---
{{- end }}