apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.codehorn.helpers.dockerDaemon.name }}
  labels:
    app: {{ .Values.codehorn.helpers.dockerDaemon.name }}
    chart: {{ $.Chart.Name }}
spec:
  replicas: {{ .Values.codehorn.helpers.dockerDaemon.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.codehorn.helpers.dockerDaemon.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.codehorn.helpers.dockerDaemon.name }}
    spec:
      volumes:
        - name: docker-volume
          persistentVolumeClaim:
            claimName: {{ .Values.codehorn.pvc.name }}

      containers:
        - name: {{ .Values.codehorn.helpers.dockerDaemon.name }}
          image: {{ .Values.codehorn.helpers.dockerDaemon.image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true

          volumeMounts:
            - name: docker-volume
              mountPath: {{ .Values.codehorn.helpers.dockerDaemon.volumeMountBasePath }}

          ports:
            - containerPort: 2375

          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
            - name: DOCKER_HOST
              value: tcp://localhost:2375

          command:
            - dockerd
            - --host=tcp://0.0.0.0:2375
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.codehorn.helpers.dockerDaemon.name }}
spec:
  clusterIp: None
  selector:
    app: {{ .Values.codehorn.helpers.dockerDaemon.name }}
  ports:
    - port: 80
      targetPort: 2375
---